import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

const SAGE = [124, 154, 126]
const CLAY = [193, 127, 94]
const INK = [44, 44, 42]
const MUTED = [136, 135, 128]
const LIGHT = [239, 244, 239]
const WHITE = [255, 255, 255]

function addHeader(doc, title, subtitle) {
  // Sage bar
  doc.setFillColor(...SAGE)
  doc.rect(0, 0, 210, 22, 'F')
  // Logo text
  doc.setTextColor(...WHITE)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.text('StageFlow', 14, 14)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.text('Home Staging CRM', 14, 19)
  // Right title
  doc.setFontSize(10)
  doc.text(title, 196, 12, { align: 'right' })
  doc.setFontSize(8)
  doc.text(subtitle, 196, 18, { align: 'right' })
  doc.setTextColor(...INK)
}

function addFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFillColor(250, 248, 245)
    doc.rect(0, 284, 210, 13, 'F')
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...MUTED)
    doc.text('Generated by StageFlow · Home Staging CRM', 14, 291)
    doc.text(`Page ${i} of ${pageCount}`, 196, 291, { align: 'right' })
    doc.setTextColor(...INK)
  }
}

export function generateJobSheetPDF(job, realtor) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  addHeader(doc, 'JOB SHEET', `Job #${job.id}`)

  // Property block
  doc.setFillColor(...LIGHT)
  doc.roundedRect(14, 28, 182, 32, 3, 3, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(15)
  doc.setTextColor(...INK)
  doc.text(job.address, 22, 39)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...MUTED)
  doc.text(`${job.city}, ${job.state || 'IL'}`, 22, 46)

  // Status badge
  const statusColors = {
    Active: SAGE, Scheduled: CLAY, Complete: MUTED, 'Under Review': [229, 168, 85]
  }
  const sColor = statusColors[job.status] || MUTED
  doc.setFillColor(...sColor)
  doc.roundedRect(22, 49, 28, 7, 2, 2, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7)
  doc.setTextColor(...WHITE)
  doc.text(job.status.toUpperCase(), 36, 54.2, { align: 'center' })
  doc.setTextColor(...INK)

  // Date
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(...MUTED)
  doc.text(`Date: ${job.date}`, 175, 54, { align: 'right' })
  doc.setTextColor(...INK)

  // Two-col info
  let y = 68
  const col1 = 14, col2 = 111

  // Realtor info
  doc.setFillColor(250, 248, 245)
  doc.roundedRect(col1, y, 90, 28, 2, 2, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(...MUTED)
  doc.text('REALTOR', col1 + 6, y + 7)
  doc.setTextColor(...INK)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text(realtor?.name || job.realtor, col1 + 6, y + 15)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(...MUTED)
  doc.text(realtor?.agency || '', col1 + 6, y + 21)
  if (realtor?.phone) doc.text(realtor.phone, col1 + 6, y + 26)
  doc.setTextColor(...INK)

  // Items count
  doc.setFillColor(250, 248, 245)
  doc.roundedRect(col2, y, 85, 28, 2, 2, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(...MUTED)
  doc.text('ITEMS STAGED', col2 + 6, y + 7)
  doc.setTextColor(...INK)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.text(String(job.items?.length || 0), col2 + 6, y + 22)
  doc.setTextColor(...INK)

  y += 36

  // Items table
  if (job.items?.length > 0) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...MUTED)
    doc.text('STAGED ITEMS', 14, y)
    doc.setTextColor(...INK)
    y += 4

    autoTable(doc, {
      startY: y,
      head: [['#', 'Item Description']],
      body: job.items.map((item, i) => [i + 1, item]),
      theme: 'plain',
      headStyles: { fillColor: SAGE, textColor: WHITE, fontSize: 8, fontStyle: 'bold', cellPadding: { top: 5, bottom: 5, left: 6, right: 6 } },
      bodyStyles: { fontSize: 10, cellPadding: { top: 5, bottom: 5, left: 6, right: 6 } },
      alternateRowStyles: { fillColor: [250, 248, 245] },
      columnStyles: { 0: { cellWidth: 12, halign: 'center', textColor: MUTED } },
      margin: { left: 14, right: 14 },
    })
    y = doc.lastAutoTable.finalY + 10
  }

  // Notes
  if (job.notes) {
    doc.setFillColor(248, 237, 229)
    doc.roundedRect(14, y, 182, Math.max(20, doc.splitTextToSize(job.notes, 172).length * 5 + 14), 3, 3, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.setTextColor(...MUTED)
    doc.text('NOTES', 22, y + 8)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(...INK)
    const lines = doc.splitTextToSize(job.notes, 172)
    doc.text(lines, 22, y + 15)
  }

  addFooter(doc)
  doc.save(`JobSheet_${job.address.replace(/\s+/g, '_')}.pdf`)
}

export function generateInvoicePDF(invoice, job) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  addHeader(doc, 'INVOICE', `#INV-${String(invoice.id).padStart(4, '0')}`)

  // Invoice header block
  let y = 30

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(...INK)
  doc.text('Invoice', 14, y + 10)

  // Status pill
  const sMap = { Paid: [58, 109, 17], Pending: [139, 78, 42], Overdue: [155, 38, 38] }
  const sCol = sMap[invoice.status] || MUTED
  doc.setFillColor(sCol[0], sCol[1], sCol[2])
  doc.roundedRect(14, y + 14, 24, 7, 2, 2, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7)
  doc.setTextColor(255, 255, 255)
  doc.text(invoice.status.toUpperCase(), 26, y + 19.2, { align: 'center' })
  doc.setTextColor(...INK)

  // Right side amounts
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(32)
  doc.setTextColor(...SAGE)
  doc.text(`$${invoice.amount.toLocaleString()}`, 196, y + 12, { align: 'right' })
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(...MUTED)
  doc.text('Total Amount', 196, y + 19, { align: 'right' })
  doc.setTextColor(...INK)

  y += 32

  // Info grid
  doc.setFillColor(250, 248, 245)
  doc.roundedRect(14, y, 182, 38, 3, 3, 'F')

  // Bill to
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(...MUTED)
  doc.text('BILLED TO', 22, y + 9)
  doc.setTextColor(...INK)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text(invoice.realtor, 22, y + 17)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(...MUTED)
  doc.text(invoice.address, 22, y + 24)
  doc.setTextColor(...INK)

  // Dates
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(...MUTED)
  doc.text('INVOICE DATE', 120, y + 9)
  doc.setTextColor(...INK)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(invoice.date, 120, y + 17)

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(...MUTED)
  doc.text('DUE DATE', 120, y + 26)
  doc.setTextColor(...INK)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(invoice.dueDate || invoice.date, 120, y + 34)

  y += 46

  // Services table
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...MUTED)
  doc.text('SERVICES', 14, y)
  doc.setTextColor(...INK)
  y += 4

  const bodyRows = [
    ['Home Staging Services', invoice.address, `$${invoice.amount.toLocaleString()}`],
  ]
  if (job?.items?.length) {
    bodyRows.push(['Items Staged', job.items.slice(0, 5).join(', ') + (job.items.length > 5 ? ` +${job.items.length - 5} more` : ''), ''])
  }
  if (invoice.notes) {
    bodyRows.push(['Notes', invoice.notes, ''])
  }

  autoTable(doc, {
    startY: y,
    head: [['Description', 'Details', 'Amount']],
    body: bodyRows,
    theme: 'plain',
    headStyles: { fillColor: SAGE, textColor: WHITE, fontSize: 8, fontStyle: 'bold', cellPadding: { top: 5, bottom: 5, left: 6, right: 6 } },
    bodyStyles: { fontSize: 10, cellPadding: { top: 6, bottom: 6, left: 6, right: 6 } },
    alternateRowStyles: { fillColor: [250, 248, 245] },
    columnStyles: { 0: { cellWidth: 44 }, 2: { cellWidth: 30, halign: 'right', fontStyle: 'bold' } },
    margin: { left: 14, right: 14 },
  })

  y = doc.lastAutoTable.finalY + 6

  // Total row
  doc.setFillColor(...SAGE)
  doc.roundedRect(130, y, 66, 14, 2, 2, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(...WHITE)
  doc.text('TOTAL DUE', 138, y + 9)
  doc.text(`$${invoice.amount.toLocaleString()}`, 192, y + 9, { align: 'right' })
  doc.setTextColor(...INK)

  y += 24
  // Thank you note
  doc.setFont('helvetica', 'italic')
  doc.setFontSize(10)
  doc.setTextColor(...MUTED)
  doc.text('Thank you for your business! Please remit payment by the due date above.', 105, y, { align: 'center' })

  addFooter(doc)
  doc.save(`Invoice_${String(invoice.id).padStart(4, '0')}_${invoice.realtor.replace(/\s+/g, '_')}.pdf`)
}
